# Render Blueprint for Next.js App Router project
# Docs: https://render.com/docs/deploy-nextjs-app

services:
  - type: web
    name: devinelamusique
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      # Optional: uncomment to enable Next.js telemetry during build
      # - key: NEXT_TELEMETRY_DISABLED
      #   value: "1"
    healthCheckPath: /
    autoDeploy: true
    
    # If you use environment variables (API keys, etc.), add them here or in Render dashboard
    # envVars:
    #   - key: SOME_SECRET
    #     sync: false
